---
- hosts: localhost
  gather_facts: false
  vars:
      region: "us-west-2"
      instance_type: "t2.micro"
      ami: "ami-08692d171e3cf02d6"  # Ubuntu 16.04 LTS
      #ami: "ami-8f78c2f7"  # Ubuntu 14.04 LTS
      keypair: "ramkeynew" # pem file name
  tasks:
  - ec2:
     key_name: "{{ keypair }}"
     instance_type: "{{ instance_type }}"
     image: "{{ ami }}"
     user_data: "{{ lookup('file', 'userdata.sh') }}"
     #user_data: "{{ lookup('file', 'tomcat8in16.04ubuntu.sh') }}"
     region: "{{ region }}"
     wait: yes
#     group: ram_aws_security_grp 
     #group: ram_awsce 
     count: 1
     count_tag:
            Name: ram
     instance_tags:
            Name: ram
    register: ec2
